project:
  type: website
  output-dir: docs

website:
  title: "Luna Catalán"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full



