project:
  type: website
  output-dir: docs

website:
  #favicon: # gotta make one
  navbar:
    title: false # title on top left corner
    #logo: #file/path/to/logo.png
    #logo-alt: "Luna Catalán"
    right:
      - href: index.qmd
        text: Home # use text options to update name
      - href: resources.qmd
        text: About
      - icon: github # icons
        href: https://github.com/lunacatalan
  page-footer: 
    background: light
    left: 
      - "Copyright 2021, Luna Catalán"
    right:
      - icon: github # icons
        href: https://github.com/lunacatalan

format:
  html:
    theme: 
      - styles.scss
    mainfont: Montserrat
    css: styles.css
    toc: true
    page-layout: full



